In [2]:
import tensorflow as tf
print(tf.__version__)

2.21.0

In [3]:
import pandas as pd

In [4]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install keras-tuner

Requirement already satisfied: keras-tuner in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (1.4.8)
Requirement already satisfied: keras in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras-tuner) (3.15.0)
Requirement already satisfied: packaging in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras-tuner) (2.34.2)
Requirement already satisfied: kt-legacy in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras-tuner) (1.81.1)
Requirement already satisfied: protobuf in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras-tuner) (7.35.1)
Requirement already satisfied: typing-extensions~=4.12 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras->keras-tuner) (2.4.0)
Requirement already satisfied: numpy in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras->keras-tuner) (2.4.6)
Requirement already satisfied: rich in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras->keras-tuner) (15.0.0)
Requirement already satisfied: namex in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from requests->keras-tuner) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from requests->keras-tuner) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [6]:
train=pd.read_csv('twitter_training.csv')

In [7]:
train.shape

(74681, 4)

In [8]:
data=train.sample(15000,random_state=42)

In [9]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one

In [10]:
# Data Exploration

In [11]:
data['Positive'].value_counts()

Positive
Negative      4488
Positive      4275
Neutral       3568
Irrelevant    2669
Name: count, dtype: int64

In [12]:
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    151
dtype: int64

In [13]:
data.duplicated().sum()

np.int64(127)

In [14]:
## data cleaning

In [15]:
data=data.dropna()

In [16]:
data.isnull().sum()

2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [17]:
data.shape

(14849, 4)

In [18]:
data.drop_duplicates(inplace=True)

In [19]:
data.duplicated().sum()

np.int64(0)

In [20]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one

In [21]:
data.drop(columns=['2401','Borderlands'],inplace=True)

In [22]:
print(type(data))

<class 'pandas.DataFrame'>

In [23]:
data

         Positive im getting on borderlands and i will murder you all ,
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one
...           ...                                                ...
7757     Positive                   i can play overwatch again (bad)
3887     Negative  The base weapons of black ops Cold War are so ...
22629     Neutral  Don'don t just jump me... @CSGO... is medal. t...
66836  Irrelevant  for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434    Positive  New video later shoot premiere at 12 and its g...

[14746 rows x 2 columns]

In [24]:
data.rename(columns={'Positive':'Sentiment','im getting on borderlands and i will murder you all ,':'Tweets'},inplace=True)

In [25]:
print(type(data))

<class 'pandas.DataFrame'>

In [26]:
data=data[(data['Sentiment']=='Positive') | (data['Sentiment']=='Negative') | (data['Sentiment']=='Neutral')]

In [27]:
data

      Sentiment                                             Tweets
21704  Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008  Negative  Pay attention executive administrators. While ...
454    Positive                                                one
58076  Negative       @Rainbow6Game Server are Available in Xbox 🥺
40659  Positive  so Awesome siege attempt... strangest bleeding...
...         ...                                                ...
57537  Positive  This is not my nice way of saying what GN with...
7757   Positive                   i can play overwatch again (bad)
3887   Negative  The base weapons of black ops Cold War are so ...
22629   Neutral  Don'don t just jump me... @CSGO... is medal. t...
56434  Positive  New video later shoot premiere at 12 and its g...

[12127 rows x 2 columns]

In [28]:
dat=data.dropna(subset=['Tweets'])

In [29]:
data['Tweets'].isnull().sum()

np.int64(0)

In [30]:
data['Tweets']

21704           Yo this looks LIT! Team:GO/Overwatch combo
47008    Pay attention executive administrators. While ...
454                                                    one
58076         @Rainbow6Game Server are Available in Xbox 🥺
40659    so Awesome siege attempt... strangest bleeding...
                               ...
57537    This is not my nice way of saying what GN with...
7757                      i can play overwatch again (bad)
3887     The base weapons of black ops Cold War are so ...
22629    Don'don t just jump me... @CSGO... is medal. t...
56434    New video later shoot premiere at 12 and its g...
Name: Tweets, Length: 12127, dtype: str

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
label=LabelEncoder()

In [33]:
data['Sentiment']=label.fit_transform(data['Sentiment'])

In [34]:
data

       Sentiment                                             Tweets
21704          2         Yo this looks LIT! Team:GO/Overwatch combo
47008          0  Pay attention executive administrators. While ...
454            2                                                one
58076          0       @Rainbow6Game Server are Available in Xbox 🥺
40659          2  so Awesome siege attempt... strangest bleeding...
...          ...                                                ...
57537          2  This is not my nice way of saying what GN with...
7757           2                   i can play overwatch again (bad)
3887           0  The base weapons of black ops Cold War are so ...
22629          1  Don'don t just jump me... @CSGO... is medal. t...
56434          2  New video later shoot premiere at 12 and its g...

[12127 rows x 2 columns]

In [35]:
data.shape

(12127, 2)

In [36]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [37]:
tokenizer=Tokenizer(oov_token='Nothing')

In [38]:
tokenizer.fit_on_texts(data['Tweets'])

In [39]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'this': 11,
 'it': 12,
 'my': 13,
 'on': 14,
 'you': 15,
 'that': 16,
 'com': 17,
 'game': 18,
 'with': 19,
 'so': 20,
 'have': 21,
 'be': 22,
 'just': 23,
 'me': 24,
 'not': 25,
 'but': 26,
 'are': 27,
 'all': 28,
 'was': 29,
 'at': 30,
 '2': 31,
 'out': 32,
 'like': 33,
 'pic': 34,
 'twitter': 35,
 'your': 36,
 'from': 37,
 'get': 38,
 'now': 39,
 'as': 40,
 'we': 41,
 'good': 42,
 't': 43,
 'play': 44,
 'johnson': 45,
 'they': 46,
 'do': 47,
 'about': 48,
 'if': 49,
 'can': 50,
 'new': 51,
 'one': 52,
 'has': 53,
 'an': 54,
 'no': 55,
 'really': 56,
 'when': 57,
 "i'm": 58,
 'will': 59,
 'love': 60,
 'time': 61,
 'what': 62,
 'up': 63,
 'more': 64,
 'unk': 65,
 '3': 66,
 'some': 67,
 'why': 68,
 'still': 69,
 'shit': 70,
 'people': 71,
 "it's": 72,
 'or': 73,
 'co': 74,
 'by': 75,
 'been': 76,
 'how': 77,
 'https': 78,
 'amazon': 79,
 '’': 80,
 'microsoft': 81,
 'best': 82,
 'games': 83,
 'dead': 84,
 '1': 85,
 'facebook': 86,
 'fucking': 87,
 'playing': 88,
 'got': 89,
 'verizon': 90,
 'because': 91,
 'great': 92,
 'fuck': 93,
 'rhandlerr': 94,
 'go': 95,
 'red': 96,
 'even': 97,
 'please': 98,
 'xbox': 99,
 'who': 100,
 'see': 101,
 'them': 102,
 'us': 103,
 'home': 104,
 'back': 105,
 'much': 106,
 '5': 107,
 'only': 108,
 'google': 109,
 'going': 110,
 'there': 111,
 'had': 112,
 'am': 113,
 "can't": 114,
 'fix': 115,
 'nvidia': 116,
 's': 117,
 'borderlands': 118,
 'tv': 119,
 'would': 120,
 'their': 121,
 'after': 122,
 'fun': 123,
 'our': 124,
 '4': 125,
 'its': 126,
 'again': 127,
 'these': 128,
 'day': 129,
 'eamaddennfl': 130,
 'first': 131,
 'most': 132,
 'than': 133,
 'very': 134,
 'over': 135,
 "don't": 136,
 'fifa': 137,
 'wait': 138,
 'today': 139,
 'also': 140,
 'make': 141,
 'never': 142,
 '2020': 143,
 'here': 144,
 'pubg': 145,
 'redemption': 146,
 'then': 147,
 'twitch': 148,
 'know': 149,
 'nba2k': 150,
 'want': 151,
 'bad': 152,
 'ever': 153,
 'rainbow6game': 154,
 'think': 155,
 'thank': 156,
 'gta': 157,
 '…': 158,
 'he': 159,
 'amazing': 160,
 'every': 161,
 'damn': 162,
 'depot': 163,
 'work': 164,
 'year': 165,
 'ps5': 166,
 'played': 167,
 'thanks': 168,
 'legends': 169,
 'video': 170,
 'guys': 171,
 'x': 172,
 'getting': 173,
 'call': 174,
 'i’m': 175,
 'too': 176,
 'last': 177,
 'news': 178,
 'series': 179,
 'help': 180,
 "i've": 181,
 'any': 182,
 'world': 183,
 'warcraft': 184,
 'happy': 185,
 'down': 186,
 'into': 187,
 'well': 188,
 '10': 189,
 'while': 190,
 'black': 191,
 'league': 192,
 'v': 193,
 'being': 194,
 'years': 195,
 'u': 196,
 'overwatch': 197,
 'off': 198,
 'man': 199,
 'watch': 200,
 'looks': 201,
 'say': 202,
 'always': 203,
 'right': 204,
 'youtu': 205,
 'another': 206,
 'ghostrecon': 207,
 'live': 208,
 'did': 209,
 'finally': 210,
 'creed': 211,
 'stop': 212,
 'update': 213,
 'need': 214,
 'team': 215,
 'youtube': 216,
 'store': 217,
 'battlefield': 218,
 'actually': 219,
 'players': 220,
 'should': 221,
 'everyone': 222,
 'ass': 223,
 'via': 224,
 'money': 225,
 'made': 226,
 'his': 227,
 'look': 228,
 'next': 229,
 'fortnite': 230,
 'buy': 231,
 'csgo': 232,
 'way': 233,
 'big': 234,
 'hearthstone': 235,
 'win': 236,
 'duty': 237,
 'already': 238,
 'many': 239,
 'free': 240,
 'thing': 241,
 'better': 242,
 'could': 243,
 'which': 244,
 'take': 245,
 'since': 246,
 'playstation': 247,
 'were': 248,
 'come': 249,
 'health': 250,
 'awesome': 251,
 'wow': 252,
 'wtf': 253,
 'it’s': 254,
 'before': 255,
 'support': 256,
 'same': 257,
 'access': 258,
 'nice': 259,
 'something': 260,
 'bit': 261,
 'care': 262,
 'pc': 263,
 'hate': 264,
 'keep': 265,
 'such': 266,
 'her': 267,
 'playapex': 268,
 'other': 269,
 'online': 270,
 'done': 271,
 'gonna': 272,
 'trying': 273,
 'excited': 274,
 '20': 275,
 'having': 276,
 'ubisoft': 277,
 'ly': 278,
 'days': 279,
 'give': 280,
 'oh': 281,
 'stream': 282,
 '100': 283,
 'hey': 284,
 'baby': 285,
 'everything': 286,
 'pretty': 287,
 'both': 288,
 '6': 289,
 'cool': 290,
 'lot': 291,
 'looking': 292,
 'old': 293,
 'war': 294,
 'doing': 295,
 'long': 296,
 'check': 297,
 'account': 298,
 'does': 299,
 'where': 300,
 'top': 301,
 'start': 302,
 'life': 303,
 'im': 304,
 'someone': 305,
 'mobile': 306,
 'cyberpunk': 307,
 'through': 308,
 'card': 309,
 'nothing': 310,
 '7': 311,
 'pay': 312,
 'two': 313,
 'player': 314,
 'real': 315,
 'use': 316,
 'things': 317,
 'servers': 318,
 'him': 319,
 'powder': 320,
 'feel': 321,
 'dota': 322,
 'super': 323,
 'lol': 324,
 'working': 325,
 'phone': 326,
 'stupid': 327,
 'little': 328,
 'night': 329,
 'm': 330,
 'hope': 331,
 'those': 332,
 'service': 333,
 'problem': 334,
 'making': 335,
 'company': 336,
 'season': 337,
 'god': 338,
 'hours': 339,
 'almost': 340,
 'hell': 341,
 'makes': 342,
 'ops': 343,
 'yet': 344,
 'literally': 345,
 'until': 346,
 'week': 347,
 '2077': 348,
 'italy': 349,
 'probably': 350,
 'anyone': 351,
 'dont': 352,
 'miss': 353,
 'favorite': 354,
 'can’t': 355,
 '19': 356,
 'uk': 357,
 'cold': 358,
 'against': 359,
 'won': 360,
 'try': 361,
 'business': 362,
 'hard': 363,
 'release': 364,
 "doesn't": 365,
 'whole': 366,
 'absolutely': 367,
 'let': 368,
 'full': 369,
 'own': 370,
 'find': 371,
 'times': 372,
 'worst': 373,
 'gaming': 374,
 'lost': 375,
 'show': 376,
 'chance': 377,
 'trash': 378,
 'said': 379,
 'app': 380,
 'minutes': 381,
 'few': 382,
 'apex': 383,
 'fact': 384,
 'open': 385,
 '0': 386,
 'end': 387,
 'put': 388,
 'says': 389,
 'without': 390,
 'part': 391,
 'story': 392,
 'cant': 393,
 "that's": 394,
 'assassins': 395,
 'hit': 396,
 '2k': 397,
 'mode': 398,
 'interesting': 399,
 'stuff': 400,
 'far': 401,
 'console': 402,
 'using': 403,
 'ea': 404,
 'guy': 405,
 'sure': 406,
 'coming': 407,
 'ranked': 408,
 'wrong': 409,
 'gameplay': 410,
 'idea': 411,
 'ps4': 412,
 'callofduty': 413,
 'anything': 414,
 'gets': 415,
 'ban': 416,
 'tt': 417,
 'around': 418,
 'thought': 419,
 'maybe': 420,
 'order': 421,
 'selling': 422,
 'vaccine': 423,
 'data': 424,
 '30': 425,
 'reason': 426,
 'tell': 427,
 'friends': 428,
 '21': 429,
 'screen': 430,
 "you're": 431,
 'beautiful': 432,
 'perfect': 433,
 'million': 434,
 'soon': 435,
 'crazy': 436,
 'worth': 437,
 'enough': 438,
 '15': 439,
 'used': 440,
 'y’all': 441,
 'd': 442,
 'covid': 443,
 "y'all": 444,
 'sad': 445,
 'point': 446,
 'pro': 447,
 'madden': 448,
 'though': 449,
 'enjoy': 450,
 'tonight': 451,
 'w': 452,
 'p': 453,
 'bought': 454,
 'high': 455,
 'dota2': 456,
 'graphics': 457,
 'line': 458,
 'currently': 459,
 'went': 460,
 'talc': 461,
 "didn't": 462,
 'away': 463,
 'banned': 464,
 'watching': 465,
 'month': 466,
 'change': 467,
 'weekend': 468,
 'epic': 469,
 'may': 470,
 'system': 471,
 'forward': 472,
 'internet': 473,
 'second': 474,
 '12': 475,
 'playhearthstone': 476,
 'tried': 477,
 'ift': 478,
 'different': 479,
 'bro': 480,
 'feels': 481,
 'kill': 482,
 "i'll": 483,
 "assassin's": 484,
 'due': 485,
 'price': 486,
 'share': 487,
 'broken': 488,
 'based': 489,
 'latest': 490,
 'saying': 491,
 'grand': 492,
 'org': 493,
 'services': 494,
 'cause': 495,
 '”': 496,
 'able': 497,
 'job': 498,
 'don’t': 499,
 'ok': 500,
 'cs': 501,
 'pre': 502,
 'patch': 503,
 'took': 504,
 'comes': 505,
 'skin': 506,
 'character': 507,
 'definitely': 508,
 'ago': 509,
 'morning': 510,
 'server': 511,
 'mean': 512,
 'myself': 513,
 'homedepot': 514,
 'exciting': 515,
 'sorry': 516,
 'power': 517,
 'else': 518,
 'huge': 519,
 'terrible': 520,
 'myteam': 521,
 'wanna': 522,
 'n2k': 523,
 'instead': 524,
 'might': 525,
 'problems': 526,
 'despite': 527,
 'cod': 528,
 'level': 529,
 'post': 530,
 'came': 531,
 'sucks': 532,
 'gold': 533,
 'i’ve': 534,
 'started': 535,
 'beluba': 536,
 'must': 537,
 'net': 538,
 'apps': 539,
 'cards': 540,
 'read': 541,
 'rewards': 542,
 'content': 543,
 'finished': 544,
 'customer': 545,
 'anymore': 546,
 'products': 547,
 'she': 548,
 'wanted': 549,
 'windows': 550,
 'eu': 551,
 'during': 552,
 'guess': 553,
 'music': 554,
 '8': 555,
 'seems': 556,
 'event': 557,
 'leagueoflegends': 558,
 'updates': 559,
 'months': 560,
 'luck': 561,
 'ready': 562,
 'seen': 563,
 'needs': 564,
 'killed': 565,
 'tomorrow': 566,
 'achievement': 567,
 'dlvr': 568,
 'set': 569,
 '9': 570,
 'run': 571,
 'match': 572,
 'y': 573,
 'trailer': 574,
 'annoying': 575,
 'experience': 576,
 'later': 577,
 're': 578,
 'talk': 579,
 'remember': 580,
 'single': 581,
 "won't": 582,
 'r': 583,
 'die': 584,
 'holy': 585,
 'shot': 586,
 'seriously': 587,
 'name': 588,
 'error': 589,
 'list': 590,
 'design': 591,
 'ronnie2k': 592,
 'early': 593,
 'breakpoint': 594,
 'half': 595,
 '3080': 596,
 'hi': 597,
 'yo': 598,
 'hour': 599,
 'taken': 600,
 'step': 601,
 'living': 602,
 'yall': 603,
 'honestly': 604,
 'least': 605,
 'gone': 606,
 'rtx': 607,
 'three': 608,
 'found': 609,
 'edition': 610,
 "haven't": 611,
 'buying': 612,
 'number': 613,
 'completely': 614,
 'face': 615,
 'loved': 616,
 'warzone': 617,
 'earned': 618,
 'place': 619,
 'blizzard': 620,
 'sometimes': 621,
 'late': 622,
 'gen': 623,
 'easports': 624,
 'once': 625,
 'community': 626,
 'person': 627,
 'c': 628,
 'yes': 629,
 'e': 630,
 'videos': 631,
 'proud': 632,
 'believe': 633,
 'issue': 634,
 'don': 635,
 'book': 636,
 'class': 637,
 '•': 638,
 'issues': 639,
 'below': 640,
 'apple': 641,
 'together': 642,
 'hear': 643,
 'seeing': 644,
 'funny': 645,
 'teams': 646,
 'totally': 647,
 'small': 648,
 'called': 649,
 'movie': 650,
 'friend': 651,
 'keeps': 652,
 'fan': 653,
 'omg': 654,
 'birthday': 655,
 'pass': 656,
 'thinking': 657,
 'suck': 658,
 'bullshit': 659,
 'each': 660,
 'follow': 661,
 'code': 662,
 'city': 663,
 'hello': 664,
 'worse': 665,
 'ghost': 666,
 'review': 667,
 'complete': 668,
 'smh': 669,
 'less': 670,
 'kinda': 671,
 'major': 672,
 'released': 673,
 'retweet': 674,
 'under': 675,
 'sound': 676,
 'trump': 677,
 'switch': 678,
 'sick': 679,
 'canada': 680,
 'battle': 681,
 'leave': 682,
 'past': 683,
 'streaming': 684,
 'either': 685,
 'tech': 686,
 'bugs': 687,
 'understand': 688,
 'launch': 689,
 'incredible': 690,
 'join': 691,
 'india': 692,
 'tired': 693,
 'main': 694,
 "they're": 695,
 'daily': 696,
 'gotta': 697,
 '“': 698,
 'article': 699,
 'lmao': 700,
 'kills': 701,
 'running': 702,
 'cannot': 703,
 'link': 704,
 'yesterday': 705,
 'saw': 706,
 'odyssey': 707,
 'ai': 708,
 'action': 709,
 'instagram': 710,
 'deal': 711,
 'add': 712,
 'move': 713,
 'cute': 714,
 'received': 715,
 'bring': 716,
 'stock': 717,
 'gift': 718,
 'mind': 719,
 'joke': 720,
 'iphone': 721,
 'b': 722,
 'family': 723,
 'market': 724,
 'waiting': 725,
 'garbage': 726,
 "we're": 727,
 'starting': 728,
 'kind': 729,
 'slow': 730,
 'mad': 731,
 'house': 732,
 've': 733,
 'stay': 734,
 'global': 735,
 "what's": 736,
 'ubisoftsupport': 737,
 'means': 738,
 "let's": 739,
 'drop': 740,
 'moment': 741,
 'girl': 742,
 'entire': 743,
 'franchise': 744,
 'that’s': 745,
 'goes': 746,
 'moments': 747,
 'fps': 748,
 'technology': 749,
 'truly': 750,
 'playoverwatch': 751,
 'points': 752,
 'absolute': 753,
 'glad': 754,
 'rockstargames': 755,
 'social': 756,
 'tho': 757,
 'spent': 758,
 'id': 759,
 'page': 760,
 'commission': 761,
 'quite': 762,
 'warfare': 763,
 'coronavirus': 764,
 'hyped': 765,
 'weeks': 766,
 'o': 767,
 'insane': 768,
 'bug': 769,
 'original': 770,
 'car': 771,
 '14': 772,
 'ur': 773,
 'steam': 774,
 'history': 775,
 'cancer': 776,
 'special': 777,
 'item': 778,
 'left': 779,
 'users': 780,
 'hot': 781,
 'trust': 782,
 'sounds': 783,
 'sell': 784,
 '–': 785,
 'continue': 786,
 'j': 787,
 'close': 788,
 'okay': 789,
 'congratulations': 790,
 'decided': 791,
 'boy': 792,
 'easy': 793,
 'delayed': 794,
 'talking': 795,
 'break': 796,
 'final': 797,
 'fortnitegame': 798,
 'taking': 799,
 'toxic': 800,
 'pick': 801,
 'version': 802,
 'star': 803,
 'lots': 804,
 'walmart': 805,
 'women': 806,
 'sold': 807,
 'takes': 808,
 'wikipedia': 809,
 'turn': 810,
 'dear': 811,
 'crap': 812,
 'yeah': 813,
 'sony': 814,
 "there's": 815,
 'happened': 816,
 'kids': 817,
 'siege': 818,
 'welcome': 819,
 'decision': 820,
 'en': 821,
 'hero': 822,
 'poverty': 823,
 'ridiculous': 824,
 'modern': 825,
 'including': 826,
 'men': 827,
 'paid': 828,
 'knows': 829,
 'performance': 830,
 'told': 831,
 '99': 832,
 'enjoyed': 833,
 '24': 834,
 'redeeming': 835,
 'fans': 836,
 'connection': 837,
 'shooting': 838,
 'wins': 839,
 'digital': 840,
 'report': 841,
 'worked': 842,
 'safe': 843,
 'mut': 844,
 'bitch': 845,
 'l': 846,
 'date': 847,
 'head': 848,
 'massive': 849,
 'feeling': 850,
 'plus': 851,
 'geforce': 852,
 'true': 853,
 'packs': 854,
 'works': 855,
 'box': 856,
 'wild': 857,
 'forever': 858,
 'heart': 859,
 'death': 860,
 'biggest': 861,
 'f': 862,
 'security': 863,
 'nba': 864,
 'shut': 865,
 'yourself': 866,
 'low': 867,
 'longer': 868,
 'died': 869,
 'dope': 870,
 'sense': 871,
 'beta': 872,
 'created': 873,
 'fight': 874,
 'stuck': 875,
 'fast': 876,
 'test': 877,
 'stopped': 878,
 'felt': 879,
 'china': 880,
 'channel': 881,
 'plan': 882,
 'boring': 883,
 'art': 884,
 'plz': 885,
 '11': 886,
 'state': 887,
 'gpu': 888,
 'unit': 889,
 'nfl': 890,
 'school': 891,
 'n': 892,
 'search': 893,
 'learning': 894,
 'listen': 895,
 'ordered': 896,
 'important': 897,
 'drive': 898,
 'sweet': 899,
 'hand': 900,
 'hold': 901,
 'somehow': 902,
 'plays': 903,
 'skins': 904,
 'platform': 905,
 'delivery': 906,
 'heard': 907,
 'current': 908,
 'email': 909,
 'option': 910,
 'developers': 911,
 'between': 912,
 'football': 913,
 '13': 914,
 'till': 915,
 'matter': 916,
 'cry': 917,
 'powerful': 918,
 'map': 919,
 'lose': 920,
 'enjoying': 921,
 'spend': 922,
 'rather': 923,
 'wish': 924,
 'future': 925,
 'crashing': 926,
 'ya': 927,
 '000': 928,
 'valorant': 929,
 'racist': 930,
 '60': 931,
 'rt': 932,
 'summoners': 933,
 'word': 934,
 'demon': 935,
 'favourite': 936,
 'pls': 937,
 'fixed': 938,
 'controller': 939,
 'quit': 940,
 'bc': 941,
 'recon': 942,
 'rest': 943,
 'log': 944,
 'couple': 945,
 'chinese': 946,
 'tf': 947,
 'giving': 948,
 'government': 949,
 '50': 950,
 'inside': 951,
 'ppl': 952,
 'eahelp': 953,
 'dark': 954,
 'behind': 955,
 'calling': 956,
 'theft': 957,
 '25': 958,
 'calls': 959,
 '16': 960,
 'trial': 961,
 'especially': 962,
 'companies': 963,
 'greatest': 964,
 'within': 965,
 'website': 966,
 'random': 967,
 'white': 968,
 'brand': 969,
 'sales': 970,
 'suddenly': 971,
 'imagine': 972,
 'fantastic': 973,
 'control': 974,
 'party': 975,
 'program': 976,
 'gave': 977,
 'fake': 978,
 'cuz': 979,
 'towards': 980,
 'king': 981,
 'decent': 982,
 'edge': 983,
 'quality': 984,
 'tweet': 985,
 'shitty': 986,
 'ahead': 987,
 'pandemic': 988,
 'short': 989,
 'monday': 990,
 'create': 991,
 'customers': 992,
 'ball': 993,
 'happens': 994,
 "isn't": 995,
 'features': 996,
 'explain': 997,
 'af': 998,
 'dumb': 999,
 'finish': 1000,
 ...}

In [40]:
tokenizer.word_counts

OrderedDict([('yo', 51),
             ('this', 2399),
             ('looks', 180),
             ('lit', 14),
             ('team', 167),
             ('go', 353),
             ('overwatch', 182),
             ('combo', 8),
             ('pay', 112),
             ('attention', 10),
             ('executive', 4),
             ('administrators', 4),
             ('while', 188),
             ('your', 724),
             ('stores', 26),
             ('are', 945),
             ('taking', 35),
             ('delivery', 30),
             ('orders', 19),
             ('for', 2543),
             ('pallets', 2),
             ('of', 3209),
             ('bricks', 2),
             ('to', 4802),
             ('downtown', 2),
             ('then', 243),
             ('you', 1923),
             ('were', 145),
             ('being', 185),
             ('used', 72),
             ('in', 2564),
             ('helping', 24),
             ('the', 7261),
             ('destruction', 5),
             ('private', 10),
             ('property', 6),
             ('one', 556),
             ('rainbow6game', 231),
             ('server', 61),
             ('available', 26),
             ('xbox', 344),
             ('🥺', 9),
             ('so', 1273),
             ('awesome', 143),
             ('siege', 34),
             ('attempt', 6),
             ('strangest', 3),
             ('bleeding', 4),
             ('out', 746),
             ('spinning', 8),
             ('sequence', 2),
             ('ever', 232),
             ('s', 293),
             ('my', 2015),
             ('first', 268),
             ('squadmate', 1),
             ('john', 14),
             ('could', 151),
             ('see', 334),
             ('exactly', 16),
             ('which', 151),
             ('was', 922),
             ("i'm", 524),
             ('really', 528),
             ('looking', 122),
             ('forward', 67),
             ('game', 1503),
             ('verizon', 366),
             ('sheds', 1),
             ('81', 4),
             ('000', 29),
             ('digital', 33),
             ('tv', 285),
             ('on', 1974),
             ('black', 188),
             ('cutting', 8),
             ('escalates', 1),
             ('breitbart', 2),
             ('com', 1586),
             ('entertainment', 13),
             ('internet', 67),
             ('gave', 27),
             ('way', 157),
             ('coke', 3),
             ('show', 87),
             ('money', 160),
             ('keep', 135),
             ('ch', 2),
             ('tmmobile', 1),
             ('guys', 209),
             ('very', 261),
             ('slow', 39),
             ('town', 12),
             ('tuba', 2),
             ('fix', 302),
             ('fucking', 374),
             ('pro', 71),
             ('am', 311),
             ('can’t', 96),
             ('find', 90),
             ('no', 532),
             ('games', 382),
             ('2ksupport', 22),
             ('i', 4932),
             ('love', 523),
             ('how', 440),
             ('gives', 20),
             ('each', 45),
             ('a', 3935),
             ('new', 568),
             ('loot', 22),
             ('box', 32),
             ('playing', 374),
             ('support', 139),
             ('forgot', 26),
             ('when', 528),
             ('hated', 7),
             ('who', 341),
             ('mad', 39),
             ('about', 580),
             ('dame', 10),
             ('getting', 208),
             ('itself', 23),
             ('regular', 9),
             ('cover', 16),
             ('like', 744),
             ('kobe', 8),
             ('or', 449),
             ('get', 689),
             ('its', 277),
             ('legend', 21),
             ('edition', 50),
             ('unk', 488),
             ('disrespect', 8),
             ('y’all', 72),
             ('showed', 17),
             ('wild', 32),
             ('simpletons', 1),
             ('only', 320),
             ('lol', 106),
             ("here's", 14),
             ('montage', 6),
             ('rescuing', 1),
             ('teammate', 14),
             ('spreadlovehxly', 2),
             ('few', 86),
             ('times', 90),
             ('other', 134),
             ('day', 273),
             ('they', 593),
             ('will', 524),
             ('forever', 32),
             ('be', 1132),
             ('heart', 32),
             ('but', 963),
             ('do', 593),
             ('kinda', 44),
             ('tho', 38),
             ('5', 321),
             ('friends', 74),
             ('players', 165),
             ('pokemon', 13),
             ('borderlands', 292),
             ('p', 70),
             ('much', 322),
             ('all', 936),
             ('sims', 5),
             ('6', 123),
             ("haven't", 50),
             ('played', 216),
             ('spiderman', 3),
             ('2', 751),
             ('reignited', 1),
             ('uuuh', 2),
             ("that'm", 1),
             ('not', 1046),
             ('through', 114),
             ('with', 1441),
             ('either', 43),
             ('ciaranstrange', 3),
             ('sasspiria', 1),
             ('playstation', 146),
             ('bleh', 2),
             ('holy', 52),
             ('shit', 458),
             ('what', 514),
             ('world', 198),
             ('we', 632),
             ('omg', 46),
             ('dreamcatcher', 1),
             ('x', 209),
             ('league', 188),
             ('federals', 1),
             ('cruises', 1),
             ('paybackindia', 2),
             ('50', 28),
             ('it', 2372),
             ('also', 250),
             ('received', 40),
             ('an', 538),
             ('amazon', 404),
             ('e', 48),
             ('voucher', 6),
             ('offering', 4),
             ('inr', 2),
             ('500', 15),
             ('as', 636),
             ('payback', 6),
             ('rewards', 57),
             ('if', 579),
             ('don’t', 63),
             ('come', 144),
             ('ain’t', 13),
             ('buying', 50),
             ('china', 31),
             ('closes\xa0foxconn', 1),
             ('johnson', 609),
             ('and', 4376),
             ('samsung', 20),
             ('factories', 8),
             ('amid', 10),
             ('virus', 23),
             ('outbreak\xa0', 1),
             ('libertarianhub', 2),
             ('2020', 246),
             ('01', 23),
             ('27', 7),
             ('chi…', 1),
             ('https', 407),
             ('t', 613),
             ('co', 449),
             ('cltmh7bc2m', 2),
             ('just', 1127),
             ('spent', 38),
             ('hour', 51),
             ('at', 828),
             ('home', 323),
             ('depot', 218),
             ('renovating', 1),
             ('house', 39),
             ('expensive', 21),
             ('hell', 100),
             ('closer', 6),
             ('birthday', 46),
             ('cool', 123),
             ('exhausted', 7),
             ('from', 718),
             ('work', 218),
             ('week', 99),
             ('probably', 98),
             ('stream', 127),
             ('today', 251),
             ('i’m', 206),
             ('stoked', 4),
             ('ok', 63),
             ('dont', 97),
             ('care', 136),
             ('charge', 14),
             ('me', 1111),
             ('70', 26),
             ('too', 206),
             ('toxic', 35),
             ('masculinity', 4),
             ('sent', 26),
             ('specifically', 1),
             ('searching', 9),
             ('“men’s', 2),
             ('hair', 16),
             ('again', 276),
             ('d', 72),
             ('mean', 61),
             ('midterms', 2),
             ('because', 363),
             ('it’s', 140),
             ('late', 49),
             ('tired', 42),
             ('atvi', 3),
             ('update', 170),
             ('their', 284),
             ('most', 268),
             ('popular', 7),
             ('hearthstone', 156),
             ('is', 2893),
             ('investors', 11),
             ('should', 163),
             ('satisfied', 7),
             ('amount', 19),
             ('things', 110),
             ('company', 101),
             ('doing', 121),
             ('make', 250),
             ('more', 501),
             ('every', 221),
             ('happy', 194),
             ('enthusiastic', 4),
             ('jerseyboys', 1),
             ('now', 682),
             ('represented', 1),
             ('fb', 15),
             ('welcome', 34),
             ('chucky', 1),
             ('csgo', 158),
             ('our', 278),
             ('chef', 1),
             ('offer', 23),
             ('content', 57),
             ('various', 6),
             ('such', 135),
             ('warcraft', 197),
             ('cs', 63),
             ('valorant', 29),
             ('click', 26),
             ('here', 244),
             ('channel', 31),
             ('tinyurl', 12),
             ('y5gm9h74', 1),
             ('«', 9),
             ('weapon', 19),
             ('development', 9),
             ('sunsetting', 1),
             ('systems', 11),
             ('best', 387),
             ('news', 204),
             ("i've", 201),
             ('heard', 30),
             ('long', 121),
             ('time', 519),
             ('those', 103),
             ('that', 1715),
             ('play', 611),
             ('any', 200),
             ('multi', 4),
             ('major', 44),
             ('season', 101),
             ('strategy', 7),
             ('plan', 31),
             ('involved', 6),
             ('know', 240),
             ('transformation', 1),
             ('needed', 25),
             ('can', 573),
             ('relate', 2),
             ('glorious', 5),
             ('days', 129),
             ('mtg', 5),
             ('bring', 40),
             ('versatile', 3),
             ('creative', 8),
             ('builds', 1),
             ('problems', 59),
             ('sexual', 4),
             ('assaults', 1),
             ('educational', 3),
             ('institutions', 1),
             ('pia', 1),
             ('fake', 27),
             ('licenses', 2),
             ('baloch', 1),
             ('students', 19),
             ('arrested', 3),
             ('protested', 1),
             ('against', 95),
             ('inaccessibility', 1),
             ('215k', 1),
             ('corona', 9),
             ('cases', 5),
             ('rising', 7),
             ('christian', 2),
             ('man', 181),
             ('shot', 52),
             ('he', 224),
             ('had', 318),
             ('bought', 70),
             ('muslim', 2),
             ('majority', 2),
             ('steps', 8),
             ('taken', 51),
             ('ban', 77),
             ('pubg', 244),
             ('3', 484),
             ('these', 274),
             ('even', 347),
             ('wore', 4),
             ('tannis', 2),
             ('her', 135),
             ('handsome', 8),
             ('jack', 10),
             ('want', 236),
             ('report', 33),
             ('racist', 29),
             ('uses', 8),
             ('vile', 2),
             ('words', 13),
             ('harass', 2),
             ('legends', 213),
             ("person's", 3),
             ('id', 38),
             ('gotcha', 2),
             ('uwu', 8),
             ('xd', 19),
             ('20', 131),
             ('series', 202),
             ('dlss', 1),
             ('0', 85),
             ('graphics', 69),
             ('processors', 2),
             ('run', 54),
             ('4k', 14),
             ('speeds', 15),
             ('than', 267),
             ('60', 29),
             ('frames', 4),
             ('per', 20),
             ('second', 67),
             ('according', 6),
             ('nvidia', 300),
             ('pcg', 1),
             ('au', 10),
             ('death', 32),
             ('stran', 1),
             ('why', 475),
             ('two', 112),
             ('year', 218),
             ('old', 122),
             ('them', 329),
             ('same', 139),
             ('youtube', 167),
             ('videos', 48),
             ('ten', 14),
             ('after', 279),
             ('bored', 12),
             ('assassins', 83),
             ('creed', 171),
             ('12', 67),
             ('great', 362),
             ('finished', 57),
             ('off', 182),
             ('last', 205),
             ('red', 350),
             ('dead', 382),
             ('redemption', 244),
             ('legendary', 22),
             ('animal', 17),
             ('pre', 63),
             ('epilogue', 2),
             ('good', 626),
             ('style', 7),
             ('pic', 741),
             ('twitter', 731),
             ('uyo0gbr2bd', 1),
             ('never', 248),
             ('miss', 97),
             ('follow', 45),
             ('current', 30),
             ('updates', 55),
             ('tech', 43),
             ('covid', 72),
             ('19', 96),
             ('comments', 17),
             ('etc', 20),
             ('exc', 1),
             ('playhearthstone', 67),
             ('legit', 14),
             ('disable', 10),
             ('djinn', 1),
             ('asap', 4),
             ('crony', 1),
             ('lame', 11),
             ('boring', 31),
             ('duvalmagic', 8),
             ('gearboxofficial', 23),
             ('wanted', 56),
             ('say', 180),
             ('saying', 64),
             ('huge', 60),
             ('thank', 227),
             ('worked', 33),
             ('working', 106),
             ('wheels', 3),
             ('gearbox', 7),
             ('’', 401),
             ('ve', 39),
             ('been', 443),
             ('crushing', 8),
             ('enven', 2),
             ('months', 55),
             ('before', 140),
             ('knowing', 17),
             ('must', 58),
             ('have', 1161),
             ('real', 111),
             ('difficult', 17),
             ('biggest', 32),
             ('fifa', 253),
             ('21', 74),
             ('downgrades', 1),
             ('⏬', 1),
             ('1', 381),
             ('collab', 2),
             ('f', 32),
             ('sebfut', 1),
             ('waht', 3),
             ('kill', 66),
             ('store', 167),
             ("it's", 456),
             ('five', 22),
             ('kid', 10),
             ('microsoft', 397),
             ('wants', 23),
             ('backwards', 5),
             ('compatible', 16),
             ('console', 81),
             ('mobilesyrup', 2),
             ('05', 20),
             ('28', 20),
             ('mic…', 3),
             ('�', 4),
             ('switched', 11),
             ('got', 371),
             ('galaxy', 6),
             ('note20', 1),
             ('ultra', 10),
             ('decision', 34),
             ('made', 160),
             ("y'all", 72),
             ("ain't", 9),
             ('help', 202),
             ('bokchoy', 1),
             ('request', 16),
             ('forget', 17),
             ('gonna', 133),
             ('google', 320),
             ('tube', 1),
             ('cook', 3),
             ('nasty', 10),
             ('kissing', 1),
             ('rt', 29),
             ('cragon', 1),
             ('myself', 61),
             ('dracula', 1),
             ('masquerade', 2),
             ('origins', 10),
             ('deus', 1),
             ('ex', 12),
             ('human', 21),
             ('revolution', 2),
             ('harry', 3),
             ('breath', 8),
             ('og', 9),
             ('leisure', 1),
             ('suit', 8),
             ('corps', 4),
             ("don't", 254),
             ('judge', 7),
             ('fluffbrawl', 1),
             ('killerxkween91', 1),
             ('itslexitaylor', 1),
             ('jbirdsgaming', 1),
             ('wtty', 1),
             ('gamewrexham', 2),
             ('gamedigital', 2),
             ('email', 30),
             ('stay', 39),
             ('safe', 33),
             ('thanks', 214),
             ('industry', 11),
             ('uk', 96),
             ('restart', 21),
             ('by', 444),
             ('9th', 4),
             ('gen', 49),
             ('still', 460),
             ('iffy', 2),
             ('malphite', 2),
             ('shard', 3),
             ('art', 31),
             ('war', 122),
             ('monolith', 2),
             ('always', 180),
             ('hard', 94),
             ('pick', 35),
             ('attack', 17),
             ('physical', 9),
             ('defense', 26),
             ('magic', 21),
             ('difficulty', 9),
             ('life', 116),
             ('give', 129),
             ('700', 5),
             ('bad', 233),
             ("can't", 307),
             ('dang', 12),
             ('thing', 153),
             ('stock', 40),
             ('plz', 31),
             ('bleepincomputer', 1),
             ('flash', 7),
             ('released', 44),
             ('security', 32),
             ("mysterious'spoofing", 1),
             ("virus'", 1),
             ('windows', 56),
             ('11', 31),
             ('tracked', 1),
             ('cve', 2),
             ('1464', 1),
             ('mention', 14),
             ('discovered', 10),
             ('version', 35),
             ('acknowledgement', 2),
             ('page', 38),
             ('ir', 1),
             ('msrc', 1),
             ('en', 34),
             ('us', 329),
             ('security…', 1),
             ('…', 225),
             ('youre', 7),
             ('throttling', 4),
             ('shame', 25),
             ('schooling', 2),
             ('people', 457),
             ('option', 30),
             ('nothing', 113),
             ("nvidia's", 14),
             ('shares', 11),
             ('rises', 5),
             ('toward', 3),
             ('record', 12),
             ('high', 70),
             ('bernstein', 1),
             ('turns', 13),
             ('bullish', 2),
             ('cuts', 3),
             ('price', 65),
             ('target', 18),
             ('mktw', 2),
             ('net', 58),
             ('32fx3km', 1),
             ('initial', 5),
             ('state', 31),
             ('alabama', 1),
             ('blank', 8),
             ('im', 116),
             ('wasting', 8),
             ('dota', 108),
             ('chick', 4),
             ('insane', 37),
             ('makes', 100),
             ('upgrade', 19),
             ('gpu', 31),
             ('video', 212),
             ('inside', 28),
             ('crashes', 25),
             ('would', 285),
             ('call', 207),
             ('videogamecrashception', 2),
             ('need', 170),
             ('leo', 4),
             ('youtu', 177),
             ('h9jup8kt9wu', 3),
             ('beautiful', 73),
             ('online', 134),
             ('order', 76),
             ('homedepot', 61),
             ('perfect', 73),
             ('→', 7),
             ('eljeeeey', 1),
             ('entering', 22),
             ('grand', 64),
             ('summoners', 29),
             ('watch', 181),
             ('won', 95),
             ('100', 126),
             ('gift', 40),
             ('card', 114),
             ('retweet', 44),
             ('everyday', 21),
             ('another', 176),
             ('chance', 87),
             ('win', 156),
             ('gs', 20),
             ('global', 39),
             ('free', 154),
             ('golden', 25),
             ('kamuy', 7),
             ('unit', 31),
             ('ylnbixjdii', 1),
             ('tile', 3),
             ('enjoyable', 9),
             ('wonderful', 19),
             ('hotel', 4),
             ('throughout', 12),
             ('madden', 71),
             ('nfl', 31),
             ('4', 278),
             ('ps4', 78),
             ('39', 6),
             ('95', 7),
             ('ebay', 21),

In [41]:
tokenizer.document_count

12127

In [42]:
len(tokenizer.word_index)

17872

In [43]:
sequences=tokenizer.texts_to_sequences(data['Tweets'])

In [44]:
sequences

[[598, 11, 201, 1679, 215, 95, 197, 2525],
 [312,
  2162,
  4024,
  4025,
  190,
  36,
  1008,
  27,
  799,
  906,
  1328,
  10,
  6523,
  7,
  6524,
  4,
  6525,
  147,
  15,
  248,
  194,
  440,
  9,
  1081,
  2,
  3484,
  7,
  2163,
  3098],
 [52],
 [154, 511, 27, 1009, 9, 99, 2323],
 [20,
  251,
  818,
  3099,
  4872,
  4026,
  32,
  2526,
  6526,
  153,
  117,
  13,
  131,
  10124,
  1680,
  243,
  101,
  2,
  2526,
  1519,
  244,
  29,
  251],
 [58, 56, 292, 472, 4, 2, 18],
 [90,
  10125,
  4027,
  928,
  840,
  119,
  14,
  2,
  191,
  2527,
  10126,
  6527,
  17,
  1774,
  191,
  473,
  90,
  977,
  233,
  4,
  4873,
  376,
  36,
  225,
  4,
  90,
  265,
  14,
  2527,
  2,
  6528],
 [10127, 15, 171, 27, 134, 730, 9, 2, 1884, 7, 6529],
 [115, 2, 87, 447, 113, 355, 371, 55, 83, 1170],
 [3, 60, 77, 197, 1260, 15, 660, 6, 51, 1171, 856, 10, 88, 256],
 [1010, 57, 3, 2791, 197],
 [100,
  473,
  29,
  731,
  48,
  2164,
  173,
  1125,
  2324,
  1520,
  33,
  2528,
  73,
  38,
  126,
  1209,
  610,
  65,
  65,
  2,
  2529,
  441,
  1458,
  2164,
  29,
  857,
  10128,
  108,
  324],
 [1681, 13, 3100, 7, 10129, 13, 1682, 6530, 6, 382, 372, 2, 269, 129],
 [46, 59, 858, 22, 9, 13, 859, 26, 11, 47, 65, 292, 671, 1679, 757, 65],
 [107,
  428,
  107,
  220,
  1775,
  118,
  453,
  106,
  28,
  3485,
  289,
  611,
  167,
  9,
  858,
  757,
  4874,
  289,
  31,
  10130,
  6531,
  10131,
  25,
  308,
  19,
  11,
  685,
  4875,
  99,
  10132,
  247,
  6532],
 [585, 70, 62, 183, 100, 41, 9],
 [654, 13, 10133, 172, 192, 7, 10134, 10135],
 [6533, 950, 12, 140, 715, 54, 79, 630, 3101, 4028, 6534, 1588, 40, 3102, 542],
 [49, 15, 499, 249, 32, 19, 6, 2528, 610, 3, 1776, 612, 15],
 [880,
  10136,
  45,
  45,
  5,
  1261,
  2530,
  2165,
  1126,
  10137,
  6535,
  17,
  143,
  1127,
  2792,
  10138,
  78,
  43,
  74,
  6536],
 [23, 758, 54, 599, 30, 104, 163, 10139, 2, 732, 1210, 40, 341],
 [3103, 4, 13, 655, 58, 290, 19, 11],
 [3,
  113,
  20,
  2793,
  37,
  164,
  11,
  347,
  194,
  350,
  55,
  118,
  282,
  139,
  175,
  20,
  4029],
 [126, 500, 352, 262, 5, 1683, 24, 1011, 9, 18, 5, 10, 100, 176],
 [800, 4030, 1012, 24, 10140, 2325, 6537, 1521, 127, 14, 79],
 [88, 442],
 [65, 512, 6538, 91, 254, 622, 5, 175, 693],
 [4876,
  2,
  51,
  213,
  10,
  52,
  7,
  121,
  132,
  2794,
  83,
  235,
  8,
  251,
  2012,
  221,
  22,
  2795,
  19,
  2,
  1329,
  7,
  317,
  2,
  336,
  8,
  295,
  4,
  141,
  2,
  220,
  100,
  27,
  173,
  64,
  5,
  64,
  161,
  129,
  185,
  5,
  4031,
  48,
  2,
  18],
 [2,
  10141,
  215,
  8,
  39,
  140,
  10142,
  30,
  1589,
  819,
  10143,
  232,
  124,
  10144,
  59,
  1128,
  15,
  543,
  37,
  3104,
  83,
  266,
  40,
  183,
  7,
  184,
  501,
  95,
  73,
  929,
  14,
  1589,
  1013,
  144,
  10,
  2,
  881,
  1885,
  17,
  10145],
 [2326,
  1330,
  2327,
  10146,
  2013,
  8,
  350,
  2,
  82,
  178,
  181,
  907,
  9,
  6,
  296,
  61,
  332,
  7,
  15,
  16,
  44,
  182,
  4032,
  672,
  337,
  18,
  19,
  182,
  2796,
  882,
  3105,
  221,
  149,
  16,
  11,
  10147,
  8,
  1040,
  40,
  3,
  50,
  6539,
  11,
  4,
  13,
  3486,
  279,
  7,
  88,
  3487,
  5,
  235,
  11,
  59,
  716,
  64,
  4877,
  2531,
  10148,
  5],
 [526,
  857,
  4033,
  10149,
  9,
  4878,
  10150,
  10151,
  978,
  6540,
  10152,
  1331,
  4879,
  91,
  46,
  10153,
  359,
  2,
  10154,
  7,
  2,
  473,
  10155,
  2328,
  3488,
  2797,
  6541,
  199,
  586,
  91,
  159,
  112,
  454,
  6,
  732,
  9,
  6542,
  6543,
  2532,
  600,
  416,
  145],
 [28,
  66,
  7,
  128,
  27,
  24,
  3,
  97,
  4034,
  6544,
  5,
  267,
  2533,
  2166,
  37,
  2,
  118,
  30],
 [3,
  151,
  4,
  841,
  6,
  930,
  100,
  2534,
  6545,
  930,
  1777,
  4,
  6546,
  24,
  9,
  2,
  192,
  7,
  169,
  18,
  16,
  4880,
  759,
  8,
  6547,
  2535,
  1332],
 [660,
  7,
  2,
  275,
  179,
  10156,
  31,
  386,
  457,
  6548,
  50,
  571,
  9,
  1684,
  30,
  1590,
  7,
  64,
  133,
  931,
  4035,
  1262,
  474,
  3106,
  4,
  116,
  10157,
  17,
  2167,
  860,
  10158],
 [24,
  3,
  499,
  38,
  68,
  13,
  313,
  165,
  293,
  50,
  44,
  102,
  257,
  216,
  631,
  1685,
  372,
  122,
  6,
  165,
  5,
  25,
  38,
  1886,
  140,
  24,
  395,
  211,
  475,
  201,
  92],
 [544,
  198,
  2,
  177,
  96,
  84,
  146,
  31,
  1172,
  1459,
  502,
  6549,
  42,
  4,
  95,
  32,
  9,
  2798,
  34,
  35,
  17,
  10159],
 [142,
  151,
  4,
  353,
  161,
  213,
  661,
  308,
  10,
  908,
  178,
  559,
  686,
  443,
  356,
  1460,
  1263,
  10160],
 [476,
  1686,
  15,
  50,
  2168,
  171,
  10161,
  4036,
  23,
  88,
  10,
  6,
  10162,
  8,
  40,
  2014,
  40,
  12,
  8,
  883],
 [118,
  2536,
  1129,
  3,
  23,
  549,
  4,
  202,
  491,
  6,
  42,
  519,
  156,
  15,
  4,
  28,
  332,
  7,
  15,
  100,
  842,
  5,
  27,
  325,
  14,
  118,
  4881,
  5,
  2799,
  15,
  80,
  733,
  76,
  2537,
  12,
  6550,
  64,
  133,
  560,
  255,
  443,
  1461,
  39,
  77,
  12,
  28,
  537,
  21,
  76,
  315,
  1462,
  20,
  156,
  15],
 [861, 137, 429, 10163, 10164, 85, 6551, 862, 10165],
 [4882, 6, 199, 482, 19, 217, 247, 2, 17],
 [72, 33, 88, 137, 359, 6, 1173, 165, 293, 2169],
 [81,
  1130,
  2,
  99,
  179,
  172,
  4,
  22,
  13,
  132,
  3489,
  1522,
  402,
  6552,
  17,
  143,
  1264,
  1265,
  4883,
  4037],
 [2015, 4, 90, 5, 89, 2, 3107, 10166, 2170, 5, 126, 2, 82, 820, 153, 226],
 [444,
  2329,
  180,
  24,
  19,
  2,
  10167,
  1523,
  3,
  2329,
  1463,
  58,
  272,
  109,
  15,
  10168,
  4884,
  12,
  49,
  72,
  2171,
  58,
  10169,
  444,
  32],
 [932,
  10170,
  107,
  83,
  181,
  132,
  693,
  513,
  88,
  10171,
  2,
  6553,
  2172,
  10172,
  1887,
  1211,
  6554,
  96,
  84,
  146,
  1209,
  7,
  4885,
  2538,
  7,
  2,
  857,
  2330,
  10173,
  2539,
  4038,
  136,
  2800,
  24,
  10174,
  10175,
  10176,
  10177,
  10178,
  475],
 [6555,
  6556,
  23,
  89,
  2,
  909,
  734,
  843,
  28,
  5,
  168,
  10,
  194,
  251,
  10,
  2,
  2016,
  9,
  2,
  357,
  41,
  59,
  21,
  6,
  1212,
  75,
  143,
  5,
  2,
  251,
  4039,
  623],
 [19, 69, 6557, 48, 11],
 [9,
  6558,
  4886,
  884,
  7,
  294,
  2,
  6559,
  8,
  64,
  203,
  6,
  42,
  363,
  801,
  1464,
  2331,
  1014,
  9,
  1213,
  2332],
 [47],
 [142,
  9,
  13,
  303,
  21,
  3,
  549,
  4,
  280,
  6,
  336,
  3490,
  20,
  152,
  26,
  114,
  91,
  2,
  1888,
  241,
  8,
  142,
  9,
  717,
  116,
  885],
 [10179,
  2801,
  472,
  4,
  143,
  5,
  81,
  673,
  6,
  863,
  213,
  4,
  115,
  6,
  10180,
  10181,
  9,
  550,
  886,
  8,
  10182,
  40,
  6560,
  143,
  10183,
  55,
  1687,
  7,
  62,
  2173,
  12,
  8,
  14,
  802,
  6561,
  760,
  10184,
  10185,
  81,
  17,
  821,
  103,
  10186,
  158],
 [90,
  2802,
  4040,
  124,
  1590,
  1041,
  14,
  15,
  104,
  6562,
  5,
  31,
  71,
  325,
  37,
  104,
  5,
  15,
  27,
  124,
  108,
  910,
  168,
  10,
  310],
 [1688,
  2017,
  3491,
  4887,
  1889,
  455,
  122,
  10187,
  1778,
  6563,
  4888,
  486,
  1392,
  14,
  6564,
  538,
  10188],
 [13, 3492, 887, 10189, 59, 2540, 90],
 [11, 2, 177, 61, 304, 2541, 13, 61, 14, 322, 4041],
 [11, 29, 768, 342, 24, 151, 4, 1333, 13, 888],
 [49,
  6,
  170,
  18,
  951,
  6,
  170,
  18,
  1042,
  14,
  15,
  120,
  15,
  174,
  12,
  6,
  6565,
  3,
  214,
  4,
  174,
  4042,
  205,
  22,
  4889],
 [432, 432, 432, 432],
 [173, 54, 270, 421, 37, 514, 8, 2, 433, 233, 4, 38],
 [2803,
  10190,
  168,
  10,
  124,
  1174,
  4,
  492,
  933,
  200,
  2,
  170,
  4,
  101,
  49,
  15,
  360,
  6,
  283,
  79,
  718,
  309,
  674,
  1214,
  16,
  10,
  206,
  474,
  377,
  4,
  236,
  44,
  1266,
  95,
  735,
  39,
  10,
  6,
  236,
  240,
  107,
  10,
  1043,
  2804,
  889,
  2803,
  78,
  43,
  74,
  10191],
 [88,
  9,
  2,
  386,
  66,
  4890,
  7,
  192,
  7,
  169,
  8,
  20,
  2333,
  88,
  9,
  2,
  386,
  66,
  18,
  7,
  192,
  7,
  169,
  8,
  20,
  1334,
  88,
  9,
  2,
  386,
  66,
  4890,
  7,
  4043,
  7,
  169,
  8,
  20,
  2333,
  88,
  1890,
  2,
  386,
  66,
  4890,
  7,
  192,
  7,
  169,
  8,
  140,
  2333],
 [448, 890, 275, 247, 125, 412, 92, 1128, 3108, 2805, 1215, 4, 10192],
 [185, 466, 4, 22, 105, 122, 295, 62, 3, 60],
 [864,
  477,
  4,
  4044,
  5,
  1393,
  11,
  91,
  12,
  201,
  33,
  10193,
  8,
  87,
  227,
  1131,
  34,
  35,
  17,
  10194],
 [337, 125],
 [1082,
  7,
  6566,
  280,
  1779,
  1015,
  4,
  579,
  1394,
  359,
  45,
  45,
  6567,
  493,
  3493,
  7,
  453],
 [284,
  1395,
  3,
  60,
  36,
  83,
  1132,
  192,
  7,
  169,
  8,
  52,
  7,
  13,
  28,
  61,
  10195,
  83,
  3,
  23,
  60,
  12,
  182,
  377,
  3,
  243,
  361,
  1465,
  6,
  168,
  442],
 [587, 212, 12, 19, 2, 559, 413],
 [20, 632, 7, 13, 51, 6568, 6569, 4045],
 [2,
  177,
  822,
  7,
  383,
  169,
  29,
  6,
  1591,
  2542,
  10196,
  12,
  10197,
  78,
  74,
  10198],
 [952, 84, 22, 3109, 4, 24, 23, 979, 3, 89, 6, 79, 4046, 14],
 [8,
  844,
  263,
  318,
  186,
  953,
  130,
  624,
  844,
  273,
  4,
  141,
  803,
  7,
  2,
  129,
  6570,
  2018,
  5,
  265,
  173,
  2,
  448,
  429,
  769,
  14,
  263,
  224,
  282,
  34,
  1083,
  10199],
 [12, 8, 25, 2, 131, 61, 16, 2, 551, 761, 53, 600, 266, 6, 601],
 [4891, 156, 4047, 228, 3494, 14, 6571, 9, 2, 358, 294],
 [163,
  781,
  1780,
  27,
  474,
  82,
  4,
  96,
  571,
  3495,
  1044,
  407,
  9,
  30,
  613,
  85,
  6572],
 [268,
  58,
  238,
  276,
  639,
  3496,
  19,
  2,
  18,
  402,
  2806,
  4,
  21,
  6,
  2807,
  3497,
  323,
  3110,
  3498,
  4892,
  4893,
  4048,
  455,
  4894,
  387,
  2543,
  53,
  3111,
  330,
  31,
  3112,
  73,
  351,
  149,
  68,
  136,
  97,
  633,
  10200,
  117,
  2,
  263],
 [210,
  145,
  8,
  1781,
  9,
  1891,
  65,
  4,
  222,
  276,
  388,
  121,
  2174,
  9,
  11,
  92,
  820,
  75,
  6573,
  455,
  891],
 [845, 304, 4049, 2334],
 [41, 214, 6, 1216, 10, 408, 204, 449],
 [23,
  706,
  476,
  2808,
  186,
  2,
  1084,
  4,
  38,
  14,
  2,
  6574,
  77,
  10201,
  6,
  309,
  18,
  29,
  4,
  316,
  1466,
  6575,
  72,
  20,
  6576,
  4,
  101],
 [3,
  167,
  11,
  399,
  170,
  14,
  79,
  361,
  67,
  561,
  10,
  6,
  1396,
  4,
  236,
  515,
  542,
  79,
  9,
  18,
  487,
  10202],
 [130,
  98,
  9,
  11,
  229,
  213,
  444,
  1892,
  2,
  3499,
  458,
  186,
  46,
  611,
  76,
  16,
  233,
  11,
  337,
  136,
  450,
  2,
  18,
  57,
  15,
  50,
  23,
  388,
  14,
  6,
  6577,
  200,
  5,
  571,
  122,
  125,
  1524],
 [30,
  2,
  257,
  61,
  527,
  2,
  384,
  16,
  111,
  27,
  459,
  67,
  283,
  434,
  71,
  602,
  640,
  2,
  823,
  458,
  132,
  7,
  102,
  47,
  25,
  21,
  258,
  4,
  250,
  494,
  5,
  47,
  25,
  21,
  258,
  4,
  250,
  262,
  190,
  132,
  7,
  102,
  47,
  25,
  21,
  258,
  4,
  250,
  262],
 [1397,
  111,
  8,
  54,
  3113,
  2797,
  2175,
  10,
  4050,
  4051,
  4895,
  6578,
  9,
  2,
  1782,
  2335,
  243,
  12,
  22,
  1133,
  16,
  10203,
  117,
  455,
  6579,
  97,
  980,
  2,
  387,
  7,
  2,
  2335,
  165,
  8,
  6580,
  73,
  126,
  186,
  4,
  2,
  1085,
  2328,
  1126,
  6581,
  161,
  1044,
  8,
  6582,
  675,
  137,
  6583,
  4052,
  4,
  364,
  220],
 [2],
 [58,
  9,
  6,
  520,
  887,
  7,
  719,
  204,
  39,
  26,
  3,
  21,
  4,
  202,
  12,
  29,
  1398,
  58,
  323,
  274,
  48,
  736,
  110,
  14,
  19,
  1134,
  204,
  39,
  3,
  331,
  52,
  129,
  483,
  22,
  6,
  391,
  7,
  12,
  28,
  62,
  6,
  6584,
  34,
  86,
  17,
  4896],
 [168, 268, 10, 1893, 24, 187, 6, 408, 18, 19, 55, 1335, 6585, 3114],
 [2, 87, 109, 769, 30, 2, 301, 7, 11, 8, 1893, 24],
 [1045,
  29,
  266,
  6,
  42,
  165,
  10,
  83,
  2544,
  197,
  218,
  85,
  6586,
  31,
  954,
  2176,
  66,
  2545,
  125,
  4053,
  31,
  323,
  781,
  396,
  199,
  6587,
  2177,
  6,
  1467,
  165],
 [150,
  521,
  150,
  397,
  23,
  1399,
  260,
  37,
  15,
  5,
  142,
  715,
  37,
  36,
  545,
  333,
  389,
  126,
  25,
  9,
  1175,
  47,
  3,
  38,
  4,
  1267,
  13,
  242,
  362,
  6588,
  11,
  8,
  824],
 [154,
  172,
  737,
  15,
  50,
  15,
  171,
  885,
  892,
  115,
  11,
  51,
  4897,
  18,
  398,
  2,
  4898,
  4899,
  1135,
  69,
  2546,
  2,
  770,
  18,
  846,
  75,
  16,
  28,
  3115,
  738,
  12,
  80,
  117,
  20,
  123,
  26,
  3,
  50,
  80,
  16,
  43,
  44,
  546],
 [739,
  28,
  1136,
  4,
  614,
  378,
  2,
  4054,
  86,
  641,
  5,
  109,
  4055,
  16,
  4900,
  32,
  147,
  376,
  71,
  455,
  10204,
  5,
  10205,
  127,
  625,
  11,
  8,
  135,
  782,
  1400,
  14,
  1689,
  103,
  843],
 [1592,
  456,
  49,
  15,
  27,
  25,
  562,
  4,
  740,
  3116,
  352,
  47,
  12,
  2019,
  911,
  36,
  4056,
  318,
  27,
  186,
  4057,
  687,
  26,
  15,
  38,
  225,
  37,
  3116,
  20,
  126,
  500],
 [478,
  417,
  10206,
  478,
  417,
  6589,
  62,
  2,
  2178,
  21,
  46,
  271,
  4,
  2,
  2336,
  6590,
  14,
  2,
  4901,
  10207,
  11,
  8,
  68,
  136,
  33,
  230,
  46,
  1593,
  19,
  317,
  16,
  1525,
  488,
  478,
  417,
  6589],
 [11,
  3500,
  8,
  144,
  3,
  60,
  1526,
  6591,
  642,
  19,
  2,
  1016,
  14,
  12,
  57,
  12,
  23,
  1130,
  4,
  202,
  16,
  13],
 [6592,
  23,
  454,
  118,
  66,
  37,
  13,
  3117,
  403,
  36,
  2337,
  662,
  662,
  50,
  80,
  14,
  43,
  762,
  138,
  4,
  180,
  316,
  2,
  506],
 [1527, 3, 50, 80, 43, 138, 10, 153, 13, 79, 2809],
 [79,
  178,
  23,
  1268,
  6,
  2163,
  615,
  24,
  217,
  6593,
  4058,
  17,
  143,
  1017,
  1265,
  2338],
 [62, 41, 60, 204, 39, 4059, 107, 1468, 289, 65, 95, 197],
 [161,
  61,
  404,
  44,
  10208,
  418,
  24,
  3,
  580,
  2,
  520,
  741,
  57,
  3,
  29,
  229,
  4,
  239,
  6594,
  2339,
  7,
  2,
  626,
  9,
  2,
  41,
  27,
  218,
  85,
  981,
  124,
  626,
  170,
  404,
  17,
  83,
  10209],
 [4902, 228, 42, 10, 2, 10210],
 [4, 6595, 3118, 9, 96, 84, 146, 31, 148, 119, 4060, 6596],
 [433, 2810, 10211, 4061, 132, 4903, 1269],
 [1270,
  413,
  82,
  311,
  1401,
  48,
  528,
  467,
  13,
  719,
  2340,
  15,
  114,
  82,
  1401,
  10,
  825,
  763,
  40,
  563,
  9,
  174,
  7,
  237,
  192,
  205,
  22,
  4904,
  4905],
 [85, 3, 60, 52, 199, 34, 35, 17, 6597],
 [62, 12, 202, 102, 457, 59, 2341, 19, 12, 196, 101, 12, 70, 173, 315, 65],
 [154,
  277,
  68,
  47,
  46,
  265,
  173,
  2,
  4062,
  676,
  634,
  33,
  6598,
  244,
  656,
  676,
  3,
  221,
  643,
  2179,
  4906,
  2179,
  586,
  783,
  33,
  254,
  407,
  37,
  52,
  2180,
  57,
  254,
  206,
  2,
  108,
  233,
  4,
  115,
  12,
  2181,
  8,
  4,
  363,
  1594,
  2,
  1595],
 [3,
  221,
  142,
  688,
  4907,
  4,
  782,
  2342,
  2182,
  1894,
  30,
  222,
  564,
  109,
  10,
  2020],
 [62, 6, 432, 129, 32, 3, 114, 138, 4, 734, 4063, 5, 44, 183, 7, 184],
 [373, 507],
 [932,
  6599,
  79,
  5,
  6600,
  65,
  433,
  6601,
  2796,
  10212,
  17,
  6602,
  3501,
  10213,
  6603,
  6604,
  65,
  10214,
  4064,
  10215,
  6605,
  6606,
  6607,
  1263],
 [6,
  10216,
  1271,
  6608,
  4,
  245,
  15,
  187,
  6,
  347,
  7,
  403,
  81,
  2547,
  547,
  10,
  273,
  4,
  6609,
  2,
  857,
  10217,
  9,
  36,
  732],
 [10218, 27, 2, 373, 241, 16, 50, 1528, 9, 6, 358, 294, 912, 6610, 5, 6611],
 [154, 182, 2183, 14, 173, 191, 2184, 529, 10219, 5, 69, 352, 21, 182],
 [3,
  112,
  6,
  291,
  64,
  61,
  4,
  44,
  2811,
  139,
  5,
  2,
  64,
  3,
  44,
  2,
  18,
  2,
  64,
  6612,
  3,
  113,
  16,
  11,
  18,
  8,
  2,
  229,
  234,
  241],
 [16, 2, 229, 1272, 59, 44, 87, 137],
 [218, 66, 1895, 5, 6, 218, 654, 4902, 22, 20, 290, 52, 129],
 [81, 10220, 424, 14, 764, 2548, 4, 2, 1466, 10221, 17, 81, 10222],
 [88,
  137,
  19,
  13,
  742,
  548,
  89,
  267,
  131,
  913,
  2185,
  359,
  24,
  5,
  69,
  305,
  203,
  360,
  80,
  43,
  865,
  63],
 [66, 94, 92, 18, 15, 89, 1596, 720, 115, 12, 34, 35, 17, 10223],
 [31,
  8,
  519,
  1896,
  40,
  3,
  209,
  60,
  2812,
  1897,
  140,
  188,
  3,
  611,
  167,
  106,
  7,
  102,
  122,
  16,
  694,
  52,
  201,
  982,
  757],
 [4065,
  1137,
  11,
  18,
  365,
  38,
  182,
  64,
  543,
  122,
  2,
  1469,
  55,
  1046,
  11,
  18,
  29,
  6,
  3502],
 [11,
  8,
  6,
  363,
  52,
  91,
  695,
  20,
  4066,
  3,
  59,
  361,
  4,
  6613,
  513,
  198,
  332,
  677,
  2343,
  6614,
  6615],
 [2, 82, 4908],
 [1047,
  175,
  272,
  22,
  20,
  6616,
  49,
  1402,
  75,
  860,
  6617,
  1217,
  14,
  2,
  1138,
  12,
  6618,
  433],
 [10224, 82, 588, 3119, 1783, 112, 2, 861, 689, 7, 72, 743, 744],
 [6619,
  885,
  1781,
  230,
  3,
  203,
  60,
  641,
  547,
  23,
  33,
  6620,
  5,
  6621,
  28,
  7,
  36,
  400,
  3,
  21,
  3,
  721,
  10225,
  5,
  3,
  60,
  12,
  33,
  3,
  60,
  230,
  3,
  6622,
  3,
  25,
  21,
  6,
  412,
  73,
  6,
  191,
  99,
  73,
  6,
  678,
  4067,
  3,
  108,
  3503,
  21,
  25,
  6,
  721,
  5,
  3,
  50,
  25,
  38,
  16,
  230,
  19,
  885,
  1781,
  12,
  3,
  3120,
  15,
  98,
  885],
 [1273, 224, 81, 983, 10226, 1784, 9, 369, 4909, 398, 2334, 17, 2021, 893],
 [367, 264, 60],
 [3, 113, 283, 113, 2344, 272, 784, 11, 166, 40, 435, 40, 12, 1176],
 [25, 108, 299, 86, 1597, 36, 847, 26, 72, 140, 92, 10, 2022],
 [6623,
  210,
  454,
  513,
  6,
  1018,
  7,
  118,
  66,
  18,
  460,
  2,
  251,
  4,
  1172,
  57,
  6624,
  4068,
  12,
  367,
  565,
  12],
 [1129,
  118,
  113,
  41,
  644,
  11,
  56,
  3121,
  98,
  10227,
  24,
  175,
  158,
  175,
  173,
  3122,
  190,
  2,
  387,
  1598,
  27,
  2813,
  46,
  1599,
  5,
  111,
  248,
  1336,
  28,
  642,
  68,
  8,
  11,
  6,
  241],
 [3504, 6625],
 [93, 603, 397, 137, 845, 304, 4910, 6626, 4069],
 [3, 59, 142, 688, 4907, 4, 782, 2342, 2182, 1894, 30, 109, 5, 216, 10, 2020],
 [88, 137, 8, 203, 2, 82, 133, 110, 4, 44, 10228, 9, 1600, 223],
 [2,
  1218,
  955,
  28,
  48,
  28,
  179,
  213,
  117,
  2814,
  213,
  39,
  2345,
  1267,
  1274,
  302,
  17,
  2167,
  178,
  99,
  143,
  78,
  43,
  74,
  6627],
 [696,
  6628,
  6629,
  10229,
  45,
  379,
  12,
  112,
  2181,
  1601,
  126,
  4070,
  356,
  722,
  6630,
  278,
  6631,
  78,
  43,
  74,
  6632],
 [11,
  178,
  48,
  2,
  116,
  4071,
  179,
  8,
  2,
  132,
  515,
  181,
  563,
  48,
  374,
  28,
  165,
  34,
  35,
  17,
  10230],
 [616,
  207,
  29,
  1177,
  765,
  10,
  502,
  4072,
  2,
  1048,
  610,
  5,
  2346,
  2,
  18,
  40,
  435,
  300,
  3,
  243,
  5,
  47,
  3,
  512,
  4911,
  1898,
  11,
  277,
  31],
 [2,
  645,
  391,
  8,
  16,
  111,
  27,
  239,
  64,
  10231,
  10232,
  133,
  3123,
  5,
  3123,
  244,
  6633,
  4,
  208,
  9,
  64,
  10233,
  6634,
  5,
  46,
  6635,
  103,
  28],
 [190,
  3,
  80,
  733,
  76,
  88,
  11,
  18,
  10,
  3505,
  2347,
  195,
  3,
  80,
  330,
  679,
  1602,
  7,
  12],
 [172, 81, 550, 984, 979, 3, 136, 21, 6, 326, 34, 35, 17, 10234],
 [6],
 [10235,
  8,
  13,
  3124,
  7,
  2023,
  6636,
  4912,
  2815,
  9,
  468,
  192,
  19,
  6,
  4073,
  10236,
  215,
  404,
  10237,
  130,
  624,
  844],
 [501, 1529, 2, 93, 63, 405, 41, 21, 6, 663, 4, 2348, 94, 34, 35, 17, 10238],
 [1331,
  125,
  580,
  20,
  15,
  21,
  140,
  240,
  258,
  4,
  804,
  7,
  92,
  81,
  539,
  15,
  50,
  316,
  19,
  57,
  36,
  894,
  37,
  104,
  128,
  2186,
  631,
  50,
  2549,
  28,
  15,
  64,
  9,
  295,
  23,
  16,
  261,
  172,
  278,
  3506],
 [4913,
  2816,
  15,
  350,
  352,
  262,
  26,
  50,
  15,
  47,
  98,
  98,
  180,
  866,
  32,
  121,
  402,
  220,
  5,
  153,
  985,
  418,
  154,
  3125,
  4,
  47,
  260,
  48,
  6637,
  91,
  95,
  633,
  43,
  24,
  46,
  27,
  295,
  367,
  310,
  98,
  180,
  103,
  46,
  635,
  80,
  1530,
  43,
  895,
  4,
  103,
  6,
  1470,
  33,
  24,
  244,
  8,
  604,
  445],
 [425,
  1219,
  503,
  206,
  426,
  68,
  11,
  908,
  2175,
  980,
  208,
  333,
  8,
  1139,
  25,
  6638],
 [12, 29, 3507, 100, 8, 2, 3508, 1275, 4074, 30, 16, 86],
 [2024, 862, 7, 43, 338],
 [49, 108, 2, 6639, 9, 2817, 219, 1220, 42],
 [508, 805, 79, 8, 110, 4, 93, 15, 19, 906],
 [81,
  934,
  39,
  3509,
  313,
  4075,
  122,
  2,
  1690,
  40,
  54,
  589,
  2,
  2818,
  1019,
  278,
  6640,
  78,
  74,
  6641],
 [3510,
  17,
  2025,
  1471,
  6642,
  4914,
  476,
  4076,
  4915,
  11,
  590,
  2550,
  935,
  2551,
  3,
  23,
  226,

In [45]:
len(sequences[0])

8

In [46]:
from keras.utils import pad_sequences

In [47]:

sequences = pad_sequences(sequences, padding='pre')

In [48]:
sequences

array([[    0,     0,     0, ...,    95,   197,  2525],
       [    0,     0,     0, ...,     7,  2163,  3098],
       [    0,     0,     0, ...,     0,     0,    52],
       ...,
       [    0,     0,     0, ...,    20,   223,  6168],
       [    0,     0,     0, ...,    43,    74, 17872],
       [    0,     0,     0, ...,   792,  1031,  6492]],
      shape=(12127, 99), dtype=int32)

In [49]:
from tensorflow.keras.layers import Dense,SimpleRNN,Input,Embedding
from tensorflow.keras.models import Sequential

In [50]:
X=sequences

In [51]:
y=data['Sentiment'].values

In [52]:
X

array([[    0,     0,     0, ...,    95,   197,  2525],
       [    0,     0,     0, ...,     7,  2163,  3098],
       [    0,     0,     0, ...,     0,     0,    52],
       ...,
       [    0,     0,     0, ...,    20,   223,  6168],
       [    0,     0,     0, ...,    43,    74, 17872],
       [    0,     0,     0, ...,   792,  1031,  6492]],
      shape=(12127, 99), dtype=int32)

In [53]:
y

array([2, 0, 2, ..., 0, 1, 2], shape=(12127,))

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [56]:
X_train.shape

(9701, 99)

In [57]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(99,1),return_sequences=False))
model.add(Dense(3,activation='softmax'))

c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [58]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [60]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 19ms/step - accuracy: 0.3648 - loss: 1.1482 - val_accuracy: 0.3607 - val_loss: 1.0931
Epoch 2/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.3651 - loss: 1.0902 - val_accuracy: 0.3599 - val_loss: 1.0916
Epoch 3/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.3691 - loss: 1.0867 - val_accuracy: 0.3656 - val_loss: 1.0917
Epoch 4/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3787 - loss: 1.0858 - val_accuracy: 0.3594 - val_loss: 1.0852
Epoch 5/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.3821 - loss: 1.0853 - val_accuracy: 0.3669 - val_loss: 1.0924
Epoch 6/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.3644 - loss: 1.0924 - val_accuracy: 0.3599 - val_loss: 1.0975
Epoch 7/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3650 - loss: 1.0922 - val_accuracy: 0.3475 - val_loss: 1.0955
Epoch 8/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3627 - loss: 1.0917 - val_accuracy: 0.3627 - val_loss: 1.0955
Epoch 9/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.3672 - loss: 1.0909 - val_accuracy: 0.3627 - val_loss: 1.0949
Epoch 10/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.3607 - loss: 1.0908 - val_accuracy: 0.3636 - val_loss: 1.0943

In [61]:
vocab_size=len(tokenizer.word_index) + 1

In [62]:
vocab_size

17873

In [63]:
model_2=Sequential()
model_2.add(Input(shape=(99,)))
model_2.add(Embedding(input_dim=vocab_size,output_dim=128))
model_2.add(Dense(3,activation='softmax'))

In [64]:
model_2.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 99, 128)        │     2,287,744 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 99, 3)          │           387 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,288,131 (8.73 MB)

 Trainable params: 2,288,131 (8.73 MB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model_final=Sequential([Embedding(input_dim=vocab_size,output_dim=128,input_length=99,mask_zero=True),
SimpleRNN(32),Dense(3,activation='softmax')])

c:\Users\Lenovo\anaconda3\envs\dl311\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [66]:
model_final.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [67]:
model_final.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 9s 43ms/step - accuracy: 0.5455 - loss: 0.9460 - val_accuracy: 0.6933 - val_loss: 0.7566
Epoch 2/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - accuracy: 0.8758 - loss: 0.3819 - val_accuracy: 0.7234 - val_loss: 0.7019
Epoch 3/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9576 - loss: 0.1291 - val_accuracy: 0.7259 - val_loss: 0.7573
Epoch 4/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 42ms/step - accuracy: 0.9747 - loss: 0.0707 - val_accuracy: 0.7069 - val_loss: 0.9024
Epoch 5/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9778 - loss: 0.0551 - val_accuracy: 0.7267 - val_loss: 0.8941
Epoch 6/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9800 - loss: 0.0456 - val_accuracy: 0.7259 - val_loss: 0.9487
Epoch 7/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9814 - loss: 0.0422 - val_accuracy: 0.7156 - val_loss: 1.0012
Epoch 8/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 0.9810 - loss: 0.0402 - val_accuracy: 0.7275 - val_loss: 1.0428
Epoch 9/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9820 - loss: 0.0380 - val_accuracy: 0.7214 - val_loss: 1.0949
Epoch 10/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9809 - loss: 0.0377 - val_accuracy: 0.7222 - val_loss: 1.0908

In [68]:
model_final.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 99, 128)        │     2,287,744 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         5,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,878,987 (26.24 MB)

 Trainable params: 2,292,995 (8.75 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 4,585,992 (17.49 MB)

In [69]:
import pickle

In [75]:
import pickle
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

In [ ]:
model_final.save('mode.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.